import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import mainpage from './mainpage';


const inter = Inter({ subsets: ['latin'] });
export default function Home() {
  return (
    <>
      <Head>
        <title>III</title>
        <meta name="description" content="Generated by the Saarock basnet" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {mainpage()}
      </main>

    </>
  )
}
